// <auto-generated />
using System;
using Make.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Make.Migrations
{
    [DbContext(typeof(MakeContext))]
    [Migration("20190812205750_dsjfsdjfsjdf")]
    partial class dsjfsdjfsjdf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Make.Models.Comentario", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artista");

                    b.Property<DateTime>("DataComentario");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.Property<string>("Titulo");

                    b.HasKey("ComentarioId");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Make.Models.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComentarioId");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao");

                    b.Property<int>("RimelId");

                    b.Property<string>("Titulo");

                    b.HasKey("MensagemId");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("RimelId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("Make.Models.Rimel", b =>
                {
                    b.Property<int>("RimelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("RimelId");

                    b.ToTable("Rimel");
                });

            modelBuilder.Entity("Make.Models.Mensagem", b =>
                {
                    b.HasOne("Make.Models.Comentario", "Comentarios")
                        .WithMany("Mensagem")
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Make.Models.Rimel", "Rimel")
                        .WithMany("Mensagens")
                        .HasForeignKey("RimelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
