// <auto-generated />
using System;
using Make.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Make.Migrations
{
    [DbContext(typeof(MakeContext))]
    [Migration("20190808182917_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Make.Models.Comentario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artista");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.Property<DateTime>("dataComentario");

                    b.Property<int?>("mensagemID");

                    b.HasKey("ID");

                    b.HasIndex("mensagemID");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("Make.Models.Rimel", b =>
                {
                    b.Property<int>("RimelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.HasKey("RimelID");

                    b.ToTable("Rimel");
                });

            modelBuilder.Entity("Make.Models.mensagem", b =>
                {
                    b.Property<int>("mensagemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.Property<DateTime>("data");

                    b.HasKey("mensagemId");

                    b.ToTable("mensagem");
                });

            modelBuilder.Entity("Make.Models.Comentario", b =>
                {
                    b.HasOne("Make.Models.mensagem", "mensagem")
                        .WithMany()
                        .HasForeignKey("mensagemID");
                });
#pragma warning restore 612, 618
        }
    }
}
